clappr/clappr

- src/base/base_object.js
- src/base/styler.js
I can't seem to re-open #348, but this PR should fix #346 as per comments there. :+1:
> base: use default values for options

- src/base/utils.js
I've got it working with this fix !
> #369 add fullscreen support on iOs 8

- src/components/media_control/media_control.js
In facts, we cannot change how iOs works, so let's hide those controls on it !
> #375 hide volume controls on ios devices

- package.json
Update repository URLs to point to clappr organization.
> Update repository URLs on package.json

- .gitignore
- README.md
> Update documentation on README.md

- src/base/utils.js
- test/base/utils_spec.js
This time a pull request without issues...
> utils: added days to formatTime

- README.md
Adding a bit or information on how to start a local server.
> Documentation on how to start a local server.

- src/components/container/container.js
- src/components/media_control/media_control.js
Also removing unnecessary semi-colon.
> fix up this.settings attribution to avoid passing by reference

- src/playbacks/html5_video/html5_video.js
> Added 'disableVideoTagContextMenu' option

- src/playbacks/hls/hls.js
This seems to fix #594.
Clicking right at the far left of the scrub bar still results in a jump back to live though, and sometimes the handle stays stuck to the left even though it then displays "live". Will take a look at that next.
> Hls playback dvr with moving window fix

- src/components/media_control/media_control.js
- src/components/seek_time/public/seek_time.html
- src/components/seek_time/seek_time.js
- src/plugins/dvr_controls/dvr_controls.js
Also the dom elements are only updated when their values change.
> Seek time no longer jumps when duration changes (or appears/disappears)

- karma.conf.js
- webpack-base-config.js
- webpack.config.js
> Created 'webpack-base-config.js' which 'webpack.config.js' and 'karma.conf.js' use

- src/playbacks/no_op/no_op.js
- src/playbacks/no_op/public/error.html
Languages available so far English, Spanish, Portuguese
> no_op: show error message on browser's current language fixes #363

- src/playbacks/flashls/flashls.js
Expose flashls playback configuration parameters as embed options #707
> Add flashls playback configuration parameters

- src/components/container_factory/container_factory.js
- src/components/player.js
- test/player_spec.js
Just put together what I proposed in #731 
If you think there is a better way or want it tweaking that's fine.
> Added support for mime types per source

- src/plugins/seek_time/seek_time.js
So if a live stream stops being live the time will change back to counting from 0.
Closes #714
> Actual server time now only used when stream is live and has dvr

- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
So that PLAYER_READY can fired before the users requests to play the content.
> HLSJS now initialised immediately

- src/components/core/core.js
- src/components/player.js
To be consistent with other places. This changes the api, but the `isReady()` method was also only added recently.
> Change isReady() to isReady in Core and Player

- src/components/container/public/style.scss
> Fix so that cursor is hidden when idle in fullscreen

- src/plugins/poster/poster.js
> Ensure poster play button remains visible if autoplay doesn't work

- README.md
- src/components/player.js
- src/plugins/watermark/public/watermark.html
- src/plugins/watermark/public/watermark.scss
- src/plugins/watermark/watermark.js
Add watermarkLink parameter to define URL to open when the watermark is clicked
ref:https://github.com/clappr/clappr/issues/794
> watermark: add watermarkLink parameter

- src/playbacks/html5_video/html5_video.js
play method not always called (ie autoplay)
(fixes #800)
> Start playhead moving checks in playing event not play() method

- src/playbacks/html5_video/html5_video.js
This fixes issues with devices which disable autoplay, like ios. The "canplay" event fires for these devices before user interaction is required. "loadeddata", fires after user interaction has been provided.
Therefore "loadeddata" (first frame loaded) is now used to signify that loading has started. However there's also a "waiting" event, which if triggered will also signify that loading has started. The waiting event seems to be fired after user interaction when waiting is required before playback can occur. I have checked as well and on ios programmatically calling a method like play() or seek() does not trigger the 'waiting' event. I guess iOS is just ignoring these requests completely.
This means if autoplay is not requested in the player options, once the user has clicked play the …
> Html5Video playback now only buffering after first frame loaded, or user action

- src/plugins/poster/poster.js
Should also fix bug where play icon not visible on devices where autoplay is blocked, when autoplay has been requested. Not been able to test this on a mobile yet though.
> Poster play icon now hidden during buffering

- src/playbacks/hls/hls.js
Users should not seek past the live sync point because otherwise their buffer might run out before the latest chunks arrive. Also seeking to the end of the stream, ie the getDuration() value, would sometimes go wrong and end up returning to the beginning. This seems to fix that.
> HLS playback duration now excludes content past the live sync point

- bower.json
- package.json
- webpack-base-config.js
> Update dependencies and bump min required hlsjs version

- README.md
- src/components/player.js
- src/plugins/end_video.js
> Add "exitFullscreenOnEnd"config option

- .babelrc
- package.json
Fixes https://github.com/clappr/clappr/issues/859
> Use loose class transformation in babel to support IE10

- src/playbacks/hls/hls.js
> Allow 'hlsMinimumDvrSize' to be 0

- src/playbacks/flashls/flashls.js
Previously if a user called `seek()` in a `LOADED_METADATA` event handler `playerPlay()` would then be called straight after resulting in playback starting at 0.
> Fix flasHLS playback so that LOADED_METADATA handlers called after playerPlay() call

- src/playbacks/hls/hls.js
> Run onLevelUpdated after playback type update

- src/playbacks/html_img/html_img.js
https://github.com/clappr/clappr/issues/888
> img_html: Support webp

- src/playbacks/hls/hls.js
https://github.com/clappr/clappr/issues/813
https://github.com/clappr/clappr/issues/887
> hls: Recover on network error.

- bump
- webpack.config.js
To make sure that new versions always have the latest specified versions of the dependencies at the time of release.
> Added "npm update" to bump script

- README.md
- src/components/media_control/media_control.js
- src/components/player.js
> Added "disableKeyboardShortcuts" option

- bump
This is why the dist folder still has the builds from the last version :/
> git add the dist folder in the bump script

- src/playbacks/flashls/flashls.js
- src/playbacks/flashls/flashls_events.js
Update playback type live->vod when endlist-event triggered.
See: https://github.com/mangui/flashls/pull/510
> flashls.js: Listen endlist-event and update playback type.

- src/components/player.js
I have made the following improvements in Player class:
* refactored `setVolume` and `getVolume` methods (this change should fix #677)
* changed implementation of `mute` and `unmute` methods to restore volume level
* added `start` method
* added `return this;` into interface methods so that make them chainable
> Several enhancements in Player class

- src/playbacks/no_op/no_op.js
To reduce the cpu load.
Fixes #877
> Reduce the frame rate of noop noise

- src/components/player.js
Closes https://github.com/clappr/clappr/issues/843
> Add isDvrEnabled() and isDvrInUse() to player

- src/components/player.js
- src/playbacks/html_img/html_img.js
- test/player_spec.js
Builds on https://github.com/clappr/clappr/pull/980
> private vars/methods img playback

- src/components/player.js
- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
- test/player_spec.js
This builds on https://github.com/clappr/clappr/pull/980
> private vars/methods html5 video

- src/components/container_factory/container_factory.js
useful for cases like https://github.com/tjenkinson/clappr-videocontext-playback
> Allow source to be a an instance of a class

- package.json
Until can figure out root issue.
Fixes #1015
> Cap webworkify-webpack to 1.0.6

- README.md
***1 Upvote*** **DO NOT ACCEPT THIS PR YET** we need to
* create an art for each plugin (280x160)
* order/classify them 
https://github.com/clappr/clappr/blob/b1a70cfe3ec4162221734e8ee302f1ba408a2634/README.md#external-plugins What are your thoughts?
> adds a plugin showcase

- src/components/player.js
Closes https://github.com/clappr/clappr/issues/981
> Remove is() method from Player

- doc/BUILTIN_PLUGINS.md
- package.json
- src/base/container_plugin.js
- src/base/playback.js
- src/base/utils.js
- src/components/container/container.js
- src/components/container_factory/container_factory.js
- src/components/core/core.js
- src/components/loader/loader.js
- src/playbacks/flash/flash.js
- src/playbacks/flashls/flashls.js
- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
- src/playbacks/no_op/no_op.js
- src/plugins/dvr_controls/dvr_controls.js
- src/plugins/dvr_controls/public/dvr_controls.scss
- src/plugins/dvr_controls/public/index.html
- src/plugins/strings.js
- test/plugins/strings_spec.js
Fixes #994
```javascript
var options = {
source: 'example.com/example.mpd',
language: 'pt-BR',
strings: {
'pt-BR': {
'live': 'ao vivo',
'back_to_live': 'voltar para o ao vivo',
'playback_not_supported': 'Seu navegador não supporta a reprodução deste video. Por favor, tente usar um navegador diferente.'
}
}
}
```
> Introduces internationalization (I18N)

- src/base/utils.js
- src/components/media_control/media_control.js
- test/base/utils_spec.js
E.g If player is inside an iframe without the `allowFullScreen` attribute.
Refs https://github.com/clappr/clappr/issues/1082#issuecomment-232637828
> hide fullscreen button if full screen not possible

- src/playbacks/flash/flash.js
- src/playbacks/flashls/flashls.js
- src/playbacks/hls/hls.js
Several changes to help match against extensions that happen to be uppercased.
> match lowercase based extensions

- src/playbacks/hls/hls.js
I accidentally put it back in in another PR
Fixes #1098
> remove setupHls() call in HLS constructor

- src/base/events.js
- test/base/events_spec.js
Also checks that handlers are called in the order they were registered
Closes #751
> Handle exceptions in early event handler

- src/components/media_control/media_control.js
This is required for iOS
fixes #1127
> Check if fullscreen supported on <video /> if other fullscreen checks fail

- webpack.config.js
> Revert "Export with UMD as 'clappr' and 'Clappr'"

- src/components/media_control/media_control.js
- src/playbacks/no_op/public/style.scss
- src/plugins/poster/poster.js
- test/components/media_control_spec.js
- test/plugins/poster_spec.js
Currently the poster and media control are still shown but are below the no_op div.
> Disable media control and do not show poster when Playback.NO_OP

- package.json
> Remove 'browser' field from package.json file.

- package.json
- src/components/container/container.js
- src/components/container_factory/container_factory.js
- src/components/core/core.js
- src/components/player.js
- src/playbacks/html5_video/html5_video.js
- src/plugins/sources.js
- test/components/container_factory_spec.js
- test/components/container_spec.js
- test/player_spec.js
I'll be removing some of the deps to decrease bundle size
> Remove lodash.find dep

- .travis.yml
- package.json
- src/playbacks/hls/hls.js
- webpack-base-config.js
To fix https://github.com/clappr/clappr/pull/1191#event-845886043 and https://github.com/clappr/clappr/issues/1143#issuecomment-246997927
> adds support for hls.6.x

- src/playbacks/no_op/no_op.js
- src/playbacks/no_op/public/style.scss
- src/plugins/poster/poster.js
Implements play() method for no_op playback so it behaves like other playbacks. 
Fixes #1157
> Fix no_op playback autoplay when autoPlay option is set to false

- src/components/media_control/public/media-control.html
- src/plugins/dvr_controls/public/index.html
The most basic thing possible to start to appease #863
> Provide aria labels for buttons

- doc/EXTERNAL_PLUGINS.md
Added new line with "Ad plugin" in doc/EXTERNAL_PLUGINS.md.
> ad plugin in "external plugins" list

- src/playbacks/html5_video/html5_video.js
> Fix Html5Video autoplay after playback destroyed

- doc/EXTERNAL_PLUGINS.md
The Markdown was broken. This pull fixes the Markdown problem
> Fix External Plugins Table

- src/components/browser.js
> Fix Chrome browser detection on iOS device.

- src/plugins/strings.js
Signed-off-by: Ogün Karakuş <kirk5bucuk@gmail.com>
> Add Turkish Language

- src/playbacks/html5_video/html5_video.js
> Fix 404 http error with unexpected poster value.

- package.json
- src/components/loader/loader.js
> remove lodash.uniqby

- package.json
- src/playbacks/hls/hls.js
> remove lodash.isequal

- package.json
- src/components/media_control/media_control.js
- src/plugins/strings.js
> remove lodash.merge

- package.json
https://github.com/video-dev/hls.js/releases/tag/v0.7.7
> update hlsjs to 0.7.7

- webpack-base-config.js
refs #1395 
487kb ⇨ 466kb
we can remove `process` later too, I'll keep for now because I still need to test some alternatives
> remove unnecessary nodejs polyfills

- README.md
- doc/PLAYER_ERRORS.md
I started some player fatal error handling documentation.
~~I am waiting for playback issue to be resolved (@thiagopnts is on it), i will add another example using a custom error playback to display an simple error page.~~
_DISCLAIMER: i am a bad english writer, it may contains typos 😃_
> docs: update readme and add player error documentation

- package.json
- src/base/ui_object.js
- src/components/container_factory/container_factory.js
> Remove lodash.result and lodash.isplainobject

- src/components/browser.js
Adds a detection for Microsoft Edge browsers and a new flag called `Browser.isEdge`.
Reference: https://stackoverflow.com/questions/30591706/what-is-the-user-agent-string-name-for-microsoft-edge
> browser: add Edge detection

- src/playbacks/html5_video/html5_video.js
> fix(html5_video): fix source setup with current domain(less) uri

- test/playbacks/flash_spec.js
- test/playbacks/flashls_spec.js
- test/playbacks/html5_video_spec.js
Improving playback tests to reduce the complexity
> Improving playback tests

- src/base/events.js
- test/base/events_spec.js
Adds possibility to some plugin register a global event for anyone listen
> Adds global register to Events

- src/playbacks/flashls/flashls.js
- test/playbacks/flashls_spec.js
Add method to get current time in flashls playback.
> Add missing method in flashls

- src/components/browser.js
- src/playbacks/hls/hls.js
- test/components/browser_spec.js
Get `hlsjsConfig` from `this.options.playback.hlsjsConfig` instead `this.options.playback`.
> Fix HLS playback options

- .editorconfig
Editorconf. Useful to me, probably/hopefully to others too? :) 
http://editorconfig.org/
Let me know if there are things to add/change or if something conflicts with the lint rules.
:beers:
> add editorconf

- package.json
Just a tiny change to have lint scripts also take care of all the js files at project root.
We need to apply fixes there as well then.
> Lint project root files

- src/base/events.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/hls_spec.js
- test/playbacks/html5_video_spec.js
resolve #1162 creating a new event `PLAYBACK_SEEK`
Also, fixes a test for HLS playback spec.
EDIT: Add test for new event too.
> Create PLAYBACK_SEEK event

- src/playbacks/hls/hls.js
> Suggested Fix: onReady event firing with m3u8

- src/components/player.js
- src/playbacks/hls/hls.js
- src/plugins/seek_time/seek_time.js
Hi there, 
The attempt to befriend #EXT-X-PROGRAM-DATE-TIME and actualLiveTime option.
> displaying seek time and duration according #EXT-X-PROGRAM-DATE-TIME

- public/index.html
Allows to reload the page and keep the edited code, or share the link :) 
:rocket:
> Demo page: read/write config code from/to window location hash

- src/plugins/strings.js
Get message value from fallback language (en) resolves #1641
> i18n - use message value from fallback language

- doc/BUILTIN_PLUGINS.md
> docs(plugins): Fix plugin docs for MediaControl changes in v0.3

- src/components/browser/browser.js
for..in loop would sometimes retrieve enumerable properties that do not exist on the BROWSER_DATA Array
> browser.js -> getBrowserData: replaced for..in by for..of

- doc/API_EVENTS.md
> Add example for binding to other event layers

- doc/BUILTIN_PLUGINS.md
Update documentation.
Closes #1813.
> docs(builtin-plugin): set recycleVideo default value to true

- src/plugins/poster/poster.js
> fix(poster): avoid conflict with click_to_pause plugin

- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
> fix(html5_video): ensure loop configured

- README.md
Due to a list of problems related to the autoplay feature, we're adding this new section to the docs.
- **readme.md**: Adding new section about autoplay
> docs(readme): Add Q&A answer for auto play

- .github/ISSUE_TEMPLATE/bug_report.md
Improve github bug template with more infos and attention points.
> Improve bug template info

- README.md
> Broken Links Fixed

- README.md
Found some grammatical mistakes and a few typos and fixed them.
> Fixed some grammar and types

- CONTRIBUTORS
Add myself as a new contributor to CONTRIBUTORS file: 
Bruno Corrêa <brunosantos6ft@gmail.com>
> chore: Add new contributor

- packages/clappr-core/.github/stale.yml
Adding a new tag for Stalebot to ignore an issue.
> Create a new ignore tag for stalebot

- packages/clappr-core/src/base/events/events.js
- packages/hlsjs-playback/src/hls.js
add hlsjs event FRAG_BUFFERED that can improve playback experience by optimizing buffer management
> feat(hls.js): add hlsjs frag buffered event

- README.md
For
<a href="https://app.travis-ci.com/github/clappr/clappr"><img src="https://api.travis-ci.com/clappr/clappr.svg?branch=dev"></a>
> fix:  README 

- packages/clappr-core/src/components/core/core.js
Fixes https://github.com/clappr/clappr/issues/2189
> Fix - Use playback element when no inner video tag is available
