clappr/clappr

- CONTRIBUTORS
- README.md
- src/plugins/google_analytics/google_analytics.js
- test/google_analytics_spec.js
When you used to pass a gaAccount parameter to player and didn't pass a gaTrackerName parameter, the default trackerName on GoogleAnalytics plugin was "undefined.".
I fixed that issue and added some tests to cover this GoogleAnalytics plugin's behaviour.
I also fixed the example on "README.md", because it was saying to pass a "gaTracker" parameter, but the correct parameter in the example would be "gaTrackerName".
> Fixing gaTrackerName on GoogleAnalytics plugin

- src/plugins/google_analytics/google_analytics.js
Running embedScript just after setting analytics account information, fixing problem when sending events and 'window._gat' is already defined.
> Google Analytics: Fixing embed script sequence

- src/plugins/poster/poster.js
I think $el.height() is enough and make percent height for the player able to display the big play button in a good height
> #373 Fix play icon height with player height percents

- src/playbacks/html5_video/html5_video.js
I've tested with chrome bandwidth throttling tool, it should be working fine.
> html5_video: dispatch buffering/bufferfull events when there's no enough buffer (fixes #26)

- src/plugins/watermark/public/watermark.css
Fixing position for watermark when on position top-right , top-left + set max width on image inside wrapper + set relative watermark size based on player width,
Tested on all major browsers
Test logo collection: https://drive.google.com/file/d/0Bz9apPz75nEWbWZTZWsxY3U5ZkU/view?usp=sharing
> Fixed watermark position for top-right top-left + small tweak

- src/plugins/google_analytics/google_analytics.js
Fixing :  Mixed Content: The page at '{host}' was loaded over HTTPS, but requested an insecure script 'http://www.google-analytics.com/ga.js'. This request has been blocked; the content must be served over HTTPS.
> Fixed mixed content for ga.js

- src/playbacks/no_op/no_op.js
Fixing error page due to "Uint32Array was available to IE10, but it wasn't implemented in canvas"
http://stackoverflow.com/questions/26138234/array-buffer-ie10-typed-array-constructor-argument-is-invalid
> Fixing Uint32Array is not woking on IE10 with canvas context

- src/playbacks/hls/hls.js
- test/playbacks/hls_spec.js
referencing: https://github.com/clappr/clappr/issues/519
Now that the clappr player is no longer using `window` to store variables (https://github.com/clappr/clappr/blob/0.2.1/src/main.js#L21), `window.Clappr` is not getting initialized. It seems that the Flash HLS code was missed in this upgrade.
This may not be the most elegant solution, but the flash player still needs some sort of global hook for its callbacks. I will let y'all decide a better way to solve this, but here is one solution that is working for us locally.
> initialize missing global variable

- src/plugins/spinner_three_bounce/public/spinner.scss
Previously the first 2 dots animated at the same time, not sure if this was intentional?
> fix spinner_three_bounce plugin so that dots animate in sequence

- src/components/seek_time/public/seek_time.scss
- src/components/seek_time/seek_time.js
Previously the `showTime` and `update` methods both queried `$el` for it's width, but if `$el` wasn't visible its width would be reported as 0 by the browser, resulting in the time then being shown in the wrong place. This change ensures that the element is always visible before the width queries are made, and prevents the time jumping left and right when hovering.
This also makes sure it doesn't wrap onto 2 lines when it reaches the far right of the player. Previously if it did wrap this would also cause the width to change and it would get a bit confused.
Also the previous code didn't, and this change currently doesn't listen to see if the `this.mediaControl.container.settings.seekEnabled` option changes, and then update appropriately. E.g. the user is hovering over the bar whilst …
> Fix so that seek time doesn't flicker when hovering

- src/plugins/spinner_three_bounce/spinner_three_bounce.js
Previously if `onBuffering` was called twice (which was happening for me sometimes when playing a vod hls stream), 2 timeouts would be created, and then if `onStop()` was called within the timeout interval, only the first of the timeouts would get cleared. This would then cause the loading indicator to reappear.
This should fix this but I haven't built and tested it yet as having some issues npm installing due to windows path length issues.
> three spinner bounce fix to make sure only one show timeout created

- src/playbacks/hls/hls.js
Previously was looking directly at 'source' in the options object not the resolved one.
> hls playback fix so loads correct source

- test/plugins/external_plugin_spec.js
extend method for plugins CorePlugin, Playback, ContainerPlugin, UIContainerPlugin, UICorePlugin
> Add test to extend method for exposed plugins on Clappr scope

- src/base/events.js
- src/playbacks/flashls/flashls.js
Very inspired by [Shaka](https://shaka-player-demo.appspot.com/docs/shaka.media.IStream.html#event:AdaptationEvent) I propose that we follow this  API for bitrate event parameter:
```javascript
{bitrate,bandwidth,width,height,level}
```
I'm not 100% sure about `level`, do we need that? it looks pretty coupled to HLS and maybe not useful outside this context.
> Changes bitrate event parameter

- src/playbacks/hls/hls.js
Now duration is updated whenever it changes using the documented hlsjs event.
Also fixes bug which would occur before if player was buffering as during this time hlsjs would not be able to provide the duration. Now during buffering the last known duration from the latest event is used.
Fixes #642
> Fix retrieving duration in HLS playback

- src/components/media_control/media_control.js
- src/components/seek_time/seek_time.js
Previously when a stream changes from live to dvr (after duration becomes long enough) render() would be called and then the times wouldn't be updated because the cached versions weren't cleared.
Also I was using a hidden class that never existed again.
> Fix so that SeekTime component works properly after a render() call

- src/base/events.js
- src/playbacks/hls/hls.js
We need to disptach PLAYBACK_LEVEL_SWITCH and FRAGMENT_LOADED events to make the clappr-level-selector-plugin work with HLS.js
> Dispatching PLAYBACK_LEVEL_SWITCH and FRAGMENT_LOADED events on HLS.js

- README.md
- src/components/player.js
Now the reference to a dom can be provided in the options instead of it having to be a string id.
> Added the 'parent' option

- src/components/media_control/media_control.js
- src/components/media_control/public/media-control.scss
- src/playbacks/hls/hls.js
Also the time which is now emitted in the time update events from the HLS playback is now always the actual time, no rounding occurs. This fixes #668.
As a result new logic has been added to MediaControl so that the seek bar sticks to the right if seek is disabled, or dvr is enabled but not in use.
Tested with a hls stream with sliding window, hls stream with normal dvr (no sliding window), and also a standard mp4 and all seem to work.
> Fixes in HLS playback so that playable content start point is now correct

- src/playbacks/hls/hls.js
Why do we need to explicitly skip Safari? (isn't [html5 video](https://github.com/clappr/clappr/blob/master/src/components/loader/loader.js#L47) playback [able to play](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L267) it?)
@cpeterso is it safe to assume that `!!window.MediaSource` will return `false` for all FF with disabled **MSE**?
I'm trying to test in multiple browsers:
* http://browsershots.org/https://jsfiddle.net/xd93z211/1/
It seems that is reliable.
> hlsjs: checks if MSE is enabled

- src/components/player.js
- src/playbacks/no_op/no_op.js
var playerElement = document.getElementById("player-wrapper");
var player = new Clappr.Player({
source: 'http://clappr.io/highline.mapt4',
baseUrl: '/latest',
poster: 'http://clappr.io/poster.png',
mute: true,
height: 360,
width: 640,
playbackNotSupportedMessage: 'Sorry Maxwell - your browser can't play this video'
});
player.attachTo(playerElement);
> Add support to custom playback not supported message (fixes #672)

- src/components/loader/loader.js
Currently if you load a video file but specify the mime type manually, it will be played with the audio playback because that would also be a supported playback, when I think videos should always be played with the `HTML5VideoPlayback` by default.
> Make HTML5VideoPlayback have priority over HTML5AudioPlayback

- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
Previously if the user was specifying a mime type, it was not carried through when the check was performed again in `setupSrc()`
> Fix bug which would sometimes prevent video playing when overriding mimetype

- src/playbacks/html5_video/html5_video.js
Without this if the user calls seek() from their code in a handler from clappr's LOADEDMETADATA event it will immediately get replaced with the seek in `checkInitialSeek()`
> Fire loadedmetadata event after performing an automatic seek, instead of before

- src/components/media_control/media_control.js
Previously if the user did `player.setVolume(something)` immediately after loading the player, it would get reset on the next tick due to a media control `render()`.
> Fix so that volume level doesn't get replaced by MediaControl

- src/components/core/core.js
- src/components/player.js
It's possible for the `CORE_READY` event to be fired before the `create()` method returns, making it impossible to listen to the event.
Therefore added `isReady()` method, and this is used to determine if event has been missed.
> Added core.isReady(), player.isReady(), and make sure PLAYER_READY not missed

- src/plugins/seek_time/seek_time.js
This should mimic the behaviour of the current released version.
> Show duration on seek time only when when live stream with dvr

- src/base/events.js
Started adding missing event docs.
There are a few TODOs for playback events I'm not sure about.
Also the `FRAGMENT_LOADED` event is specific to hlsjs at the moment, and it's data comes straight from the hlsjs event. Should this be standardised?
> Documenting playback events

- src/plugins/poster/poster.js
- src/plugins/poster/public/poster.scss
- test/plugins/poster_spec.js
No longer listens to `CONTAINER_STATE_BUFFERING` or `CONTAINER_STATE_BUFFERFILL` and removes some duplicated code, as I think the same is being achieved now without those events?
Tested with a hls stream and mp4 and seems to be working.
Also this fixes a bug where the poster was hidden incorrectly when #747 is being used (although that pr is currently out of date).
> Refactor poster plugin

- src/components/media_control/media_control.js
- src/playbacks/no_op/no_op.js
1. `requestAnimationFrame` leaking and killing CPU on canvas noise generator.  I was trying to re-use a single player instance across a playlist of videos (some of which were faulty during testing), and I found my CPU being pegged constantly.  Profiling found `noise()` to be the culprit.  Using `cancelAnimationFrame` (already polyfilled in utils) to take care of this.
2. `player.destroy()` fails unbinding kibo events - looks like the kibo safety check was missed in a few spots, so moved it closer to where it was needed
> Fix issues when player loaded with no source

- src/playbacks/no_op/public/style.scss
I'm not sure if this is the correct solution. Worked for me on all browsers that I initially had the issue on though. Seems to work. Someone more experienced double check it please haha
> playbackNotSupportedMessage: center text when only one line long (fixes #768)

- README.md
- src/components/media_control/media_control.js
- test/components/media_control_spec.js
* Add overridable `stylesheet` property to base MediaControl rather than creating in constructor
* Update README with sample of how to do it
* Add unit test
> Make it easier to create custom MediaControl

- README.md
- src/components/core/public/style.scss
- src/plugins/poster/poster.js
- test/plugins/poster_spec.js
The use-case is an audio-only HLS stream, which ends up using the `<video>` playback.  We want to have the poster stick around in this case, even though the source is playing.
> Allow poster to stay open for audio-only broadcasts

- src/base/events.js
- src/base/playback.js
- src/components/container/container.js
- src/components/player.js
- src/playbacks/flash/flash.js
- src/playbacks/flashls/flashls.js
- src/playbacks/hls/hls.js
- src/playbacks/html5_audio/html5_audio.js
- src/playbacks/html5_video/html5_video.js
- src/plugins/poster/poster.js
- src/plugins/poster/public/poster.scss
- src/plugins/spinner_three_bounce/spinner_three_bounce.js
- test/components/container_spec.js
- test/plugins/stats_spec.js
`PLAYBACK_BUFFERING` and `PLAYBACK_BUFFERFULL` are now only fired whenever the new 'buffering' state changes.
The `PLAYBACK_BUFFERING` event is fired when loading has started the tech isn't happy that it's got enough content to play smoothly. The `PLAYBACK_BUFFERFULL`event is fired when the tech is happy it's got enough content to play smoothly.
The `readyState` in chrome (didn't test firefox) remained at `HAVE_ENOUGH_DATA` even when it had was stuttering/stalled, so there's also a separate check to determine if the playhead is actually moving.
'PLAYBACK_BUFFERING' is triggered if the playhead isn't moving but the tech is stating that it should be playing.
`PLAYBACK_READY` is now fired when rendering finishes, as at this point`'play()` can actually be called successfully and it means it's …
> Refactored BUFFERING and BUFFERFULL events and added 'buffering' property

- src/components/media_control/media_control.js
- test/components/media_control_spec.js
(Fixes #784)
[This fix](https://github.com/clappr/clappr/compare/master...fix-volume#diff-77857a480ef013cab1d709b21f7d2ba7R341) took a while to figure out. Whenever a new container was set all the listeners this was listening to were removed, because `this.container` was `undefined` initially, and that causes everything to get removed. Intended behaviour is only listeners for the container are removed if it changes.
> Fix so that volume initialised on player load

- src/playbacks/hls/hls.js
It seems now that is responsibility of each playback to autoplay itself, since html5video already provide the basic (marking autoplay attribute).
> hls.js: play when autoPlay is true

- src/plugins/spinner_three_bounce/spinner_three_bounce.js
Can't assume the playback is still buffering a tick after the point the plugin loads.
Was causing bug when native hls used. Loading indicator was sticking on screen until play clicked on iOS. Think it might be that on ios the buffering doesn't start until play is requested.
> Fix three spinner bounce buffer handling

- src/playbacks/hls/hls.js
- src/plugins/dvr_controls/dvr_controls.js
I think previously it worked most of the time because of default browser behaviour when trying to seek to an area of the buffer where there wasn't content. When the stream had been running for a bit, sometimes there would be content at -1 seconds that hadn't been cleaned up, hence the seek back to the beginning.
(Fixes #808)
> Fix "back to live" so that it seeks explicitly to end position, not -1

- src/plugins/sources.js
This PR fixes the error:
```
%c[error]color: #ff0000;font-weight: bold; font-size: 13px;error on eventcore:containers:createdtrigger-TypeError: Object doesn't support property or method 'find'
```
Which occurs on any browser which does not support the native ES6 method 'find' on the Array prototype object. (IE10 and IE11 for example)
Per discussion with @leandromoreira this is a new PR to fix the issue described in https://github.com/clappr/clappr/pull/816
> Switched to lodash 'find' from native ES6 'find' for older browser support

- src/playbacks/html5_video/html5_video.js
This fixes a bug which would cause the play button not to reappear when clicking stop on a live stream (because hlsjs is detached, but the video element still thinks it's buffering).
I think this is more of a simple fix for now. When hlsjs is detached I don't think `buffering` being true really makes sense, but not sure at the moment how to make it `false`. Maybe on stop() the video/audio element should be destroyed and recreated so it starts fresh?
> Set buffering to false when Html5Video is stopped

- src/playbacks/base_flash_playback/base_flash_playback.js
- src/playbacks/base_flash_playback/public/flash.html
This PR fixes the issue where IE10 would not play a video through FlashLS with no errors being outputted upon clicking the play icon. See related issue: https://github.com/clappr/clappr/issues/788
The final issue turned out to be that IE10 does not load a Flash file properly if there is a classid attribute as well as a 'type' attribute.
See this link for more information:
http://blogs.adobe.com/flashplayer/2015/10/flash-player-guidance-for-internet-explorer-11-and-microsoft-edge.html
> Removed FlashLS object element type attribute for legacy IE

- src/playbacks/flashls/flashls.js
- src/playbacks/hls/hls.js
- test/playbacks/hls_spec.js
There was a null vs 0 discrepancy which caused the level selector plugin to exhibit some odd behavior.
_I need a little help here getting a test working.  I'm at the point where I'm monkeypatching hls.js, but that isn't where we want to be.  Any ideas for a more appropriate pattern? _
> Fixed bug where selected level id=0 would show AUTO

- src/base/playback.js
- src/components/container/container.js
- src/components/player.js
- src/playbacks/hls/hls.js
This returns the time that "0" now represents relative to when playback started.
Useful for plugins that want to place items in the player which correspond with a particular point in time when it's a live stream with a sliding window. The plugins will need to know how the media sliding.
It cannot be assumed that the media slides at a constant rate. It actually jumps because it maps to chunks, and the server may decide not to start removing chunks from the start of the stream until it's reached a certain duration.
Ref: https://github.com/tjenkinson/clappr-markers-plugin/issues/3
> Added "getStartTimeOffset()"

- src/plugins/seek_time/seek_time.js
When using the actualLiveTime feature on a live stream, currently the duration will be shown as the current time. This removes this as I don't think it's really useful.
@cowai you happy with this change? If you still want to be able to show the actual time as the duration it could be changed to be another config option instead.
> Hide duration (current time) if using actual time in seek time component

- src/playbacks/flashls/flashls.js
Also remove `timeUpdate()` because it doesn't appear to be used, and changed live boundary time from 5 seconds to 3 seconds to match hlsjs playback.
Fixes #837
> Fix "back to live" in flasHLS playback

- src/playbacks/hls/hls.js
A recent commit https://github.com/clappr/clappr/commit/aa4effd3b524475d2a161ceca682ca9b105c68dc changed the label of the levels from the height (e.g. 720p) to the bitrate in kbps.  This affects level selector plugins.  We should allow the plugins to decide how to format their own labels by sending everything (including height and bitrate) to the PLAYBACK_LEVELS_AVAILABLE event.
> Send the entire level object

- src/components/container/container.js
The Poster Plugin was enabling/disabling the media control bar on every buffer, bufferfull, and play events.  This caused the media control bar to show up unexpectedly (for example during hls.js's instantaneous jumps over holes in a segment).  The container now only triggers the CONTAINER_MEDIACONTROL_ENABLE and CONTAINER_MEDIACONTROL_DISABLE events when they change.
> Avoid triggering extraneous MediaControl events which can cause playbar to show unexpectedly

- src/components/core/core.js
When setting source using configure(), mimetype was null. If source had not appropriate file extension, source could not be played.
> core: fix mimetype when setting it using configure()

- bump
So that if dependencies fail to update, or there's an issue updating the package files, a push and publish can't happen.
Also specifically adds "package.json" and "bower.json" to git commit instead of everything.
First time I've really messed around with bash scripting so there might be issues. Also I haven't run it because on windows, and don't want to accidentally release something :P
> Make bump script fail on more errors than "npm test"

- src/components/player.js
After a receiving a `MEDIACONTROL_CONTAINERCHANGED` event, `stopListening()` is called and, therefore, no watch is kept on `userEvents`. To reproduce the problem:
1. Instantiate a new Player, listening to `PLAYER_PLAY` and `PLAYER_PAUSE` for example.
```es6
var player = new Clappr.Player({
source: "http://clappr.io/highline.mp4",
events: {
"onPlay": () => console.log("onPlay"),
"onPause": () => console.log("onPause")
}
});
```
2. Load a new source (or the same hehe).
```es6
player.load("http://clappr.io/highline.mp4")
```
3. That's it. We are no longer listening to `PLAYER_PLAY` and `PLAYER_PAUSE`.
Also, `eventsMapping` is now a property that can be easily extended. Any feedback is appreciated!
> Fix option event listeners

- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
Previously the times reported in the event wouldn't take into consideration the media that has slid off the start of the timeline, in the case of a hls stream with sliding window dvr.
> Report correct times in PLAYBACK_PROGRESS event when hls with dvr

- src/playbacks/hls/hls.js
The duration will initially be the actual duration until the real duration is longer the hlsjs's live sync point, then it drops back down to hide the content after the sync point (to prevent someone seeking to
a point which will cause their buffer to run out before the next chunk arrives).
This ensures that the dvr can only be enabled when the duration is not including the content after the live sync point.
Feels a little bit hacky with the duration being reduced when there is enough content, so if you can think of a better way let me know. I think the nicest would be only making the playback ready when the actual duration goes past the sync point, but this means when a live stream starts the user would be shown the buffering indicator for a while, unless the live stream was only made …
> Ensure dvr only enables when duration has stabilized

- src/playbacks/hls/hls.js
I don't think we should trigger a playback error if hlsjs is trying to fix it itself. Hlsjs will probably fire a fatal error if it tries to fix it and fails.
Also change `onError()` to `onHLSJSError()` so not to override `onError()` in `Html5Video`, and guarantee that `evt` and `data` will be from hlsjs.
This puts the functionality back to when playback error events were thrown in the last release.
> Don't trigger PLAYBACK_ERROR on non-fatal hlsjs errors

- src/playbacks/hls/hls.js
In ie11 trying to set the 'currentTime' property to a value when hlsjs hasn't initialised throws "InvalidStateError".
Fixes https://github.com/clappr/clappr/issues/954
Fixes https://github.com/clappr/clappr/issues/826
> Only invoke stop() and pause() on html5video from hls playback if hls is initialised

- src/playbacks/hls/hls.js
> Add missing event params to _recover() in Hls playback

- src/components/container_factory/container_factory.js
It thinks that {} is a class instance.
This reverts commit 3c33821c8bfffd7f2a2052ad882cc530b3c23821.
This looks like it might work but it seems like a bit of a hack.
https://github.com/jonschlinkert/is-plain-object
> Revert "Allow source to be a an instance of a class"

- src/plugins/poster/poster.js
or whilst buffering is happening (because buffering indicator will be in the same place)
Refs #998
> Fix poster play so hides on click or play event only

- src/components/core/core.js
source could be `{source, mimeType}`
> fix bug if calling load() with a single source

- src/plugins/sources.js
e.g if someone calls `load()` with an array
refs #998
> Fix 'sources' plugin so it still handles future sources

- src/base/events.js
- src/playbacks/flash/flash.js
- src/playbacks/flashls/flashls.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/flashls_spec.js
- test/playbacks/html5_video_spec.js
While working on a new [plugin](https://github.com/leandromoreira/clappr-stats) I tried to estimate the `startup` time but I couldn't, because the `PLAY` event happens after the first `BUFFERING` :P also @towerz is working in some things that will require this event.
> adds new event play_intent

- src/components/container/container.js
- test/components/container_spec.js
I noticed that calling `destroy` on core calls `destroy` twice on playback.
https://github.com/clappr/dash-shaka-playback/issues/14
Do you see any problem in this fix? I mean, only if the plugins order would matter, if we destroy a X plugin before the Playback.
> avoids call destroy twice

- src/components/media_control/public/media-control.html
- src/plugins/dvr_controls/public/index.html
***2 Upvotes*** If the player is embedded inside a `<form>` element (e.g. on an ASP.NET site where the whole page is a giant form), trying to press one of the media control buttons could fire the form submission unexpectedly, which results in strange behavior on full-screen, back to live, etc.
By changing the button type to "button" (instead of default of "submit"), tapping the button does not submit the form any more.
> Add type="button" to prevent form submission from embedded player

- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
video.paused remains true initially even if autoplay attribute set, but flips to false immediately after a play() call.
Refs #1076
> Html5Video: explicit call play() when autoPlay option

- src/plugins/google_analytics/google_analytics.js
Just simple change: Listener `Events.CONTAINER_ENDED` is registered twice in Google Analytics plugin.
> Removing duplicate event listener from google_analytics plugin

- src/playbacks/html5_video/html5_video.js
Making sure that 'video' mimetype does not pass validation in `isAudioOnly()` function.
> ensuring that isAudioOnly does not pass true for video types

- src/playbacks/html5_video/html5_video.js
In case the URL contains a uppercase character, it'll help match the mediaType list (e.g. "MP4" vs "mp4)
> Match by lowercase extensions in "_canPlay"

- src/playbacks/no_op/public/style.scss
Wasn't perfectly centred when using margin. Works when using padding.
Overflow and max-height setting means if the message is longer than the player the user will be able to scroll to see the entire message.
> Improve no-op playback styling

- src/plugins/poster/public/poster.scss
Confirmed affected browsers:
Internet Explorer 10
Safari on iOS 8.4 (iPad Air 2)
The container for the player poster did not have the Play button vertically aligned in the center.
Before:
https://www.dropbox.com/s/2hoae0yssccroc5/Screenshot%202016-08-08%2014.14.27.png?dl=0
After:
https://www.dropbox.com/s/ujv85f01xi75hzt/Screenshot%202016-08-08%2014.14.01.png?dl=0
When using flexbox with an older browser that implements an older version of the flexbox specification, prefixes must be added, in some cases, default values are different as well. See link:
https://msdn.microsoft.com/en-us/library/hh673531(v=vs.85).aspx
Prefixed values were generated with Autoprefixer: https://autoprefixer.github.io/
> Fix for flexbox container layout issues on older browsers

- src/plugins/favicon/favicon.js
previously the event listeners were removed off the new container which has no effect
> favicon: Remove event listeners from old container on change

- webpack.config.js
If it doesn't export as the same value in package.json `main` it gets complicated when using the library in another project.
E.g. In an external library webpack can set Clappr as `externals: {clappr: 'Clappr'}`. When the built dist is then loaded in a browser it ends up using `window["Clappr"]`. However, if built with another module builder and `define` or `exports` exists, then webpack inserts `require('Clappr')` instead which is wrong.
If in the external library it could be set to `externals: {clappr: 'clappr'}`, this issue wouldn't exist.
Here's an example of the top of a build which is broken (if it is included inside another module builder):
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
if(typeof exports === 'object' && typeof module === 'object') …
```
> Export with UMD as 'clappr' and 'Clappr'

- src/playbacks/hls/hls.js
So that it will increase in real time as chunks are added instead of jumping and making the whole chunk accessible when it arrives.
This works in sync with the start time which will also increase smoothly to move over chunks before they are removed.
> Duration in HLS playback is now extrapolated

- src/playbacks/html5_video/html5_video.js
- src/playbacks/html5_video/public/index.html
- test/playbacks/html5_video_spec.js
Removed adding `<source>` as I don't think this was necessary. I think the browser would look at the source list to determine what url to assign to the video tag itself, which we are always doing in `setupUrl()`. The video tag itself doesn't have a 'type' attribute which is why I think this.
This might be a solution to #1158 
**Edit:** After reading around a bit more it appears browsers get the type from the `content-type` header returned with the file. `type` exists on the `<source>`'s list so that the browser doesn't have to request each file to get the mime type header (which it would do if the `<source>`'s had the `type` missing).
> Html5Video: remove src on stop() and re-add on play()

- src/playbacks/hls/hls.js
Hi,
this fix an issue where hls.js instance is not properly destroyed if you destroy Clappr player while still playing video.
Currently, if you destroy Clappr player while playing, the hls.js still work and download http chunks (until the JS engine eventually garbage it).
Also i am ensure about using "delete" to nullify the instance (see [here](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L336)).
> Fix hls.js playback destroy.

- src/base/utils.js
There are cases when clappr is loaded via XHR (with subsequent eval) and no script tag is present in DOM. In such situation `currentScriptUrl` from `base\utils.js` will fail. I encountered this case when I run a project based on [Aurelia skeleton](https://github.com/aurelia/skeleton-navigation) `skeleton-typescript` (I suppose the problem is related to SystemJS loader but I'm not sure).
The proposed change fixes the problem.
> Fix currentScriptUrl when scripts list is empty

- src/components/media_control/media_control.js
Steps:
* disable the poster plugin
* play an HLS with no DVR (with stop button)
* stop the streaming
* expects media control to be hidden current behavior media control is shown
Thank @jkarder for this PR
> media_control: listens to stop container to toggle play

- src/plugins/poster/poster.js
- test/plugins/poster_spec.js
Adds an ability to specify a custom background for the poster plugin so people can not only specify an image, but do all kind of stuff like patterns, gradients or plain colors. I think it would be a good addition.
I guessed that I don't need to check if `poster.custom` is a string (it's implied) because there's no such checks for `poster` or `poster.url`.
Closes #1231
> Allow to pass a custom background to poster plugin

- package.json
c963ca0 (able travis to cache `node_modules`)
Note: fa6371e decision is based on `travis` tests point to newest nodejs version.
We use `npm v4.1.2` on tests/CI
> Build adjustments

- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
It adds HTML5 video element attributes to play video inline in web browsers on iOS device.
I also added a new playback option to allow Apple TV AirPlay.
@towerz i failed to find any information about `x-webkit-playsinline` parameter you added when playback `playInline` is set to true. Do you have any resource link to share please ?
> Allows HTML5 video to play inline on iOS

- src/components/media_control/media_control.js
Show media control when any key that is associated with an event is pressed is a new feature and were added more options to seek with keyboard. Now left and right arrows skips -5 or 5 seconds instead of -15 or 15, shift + right or left arrow skips 10 and shift + ctrl + left or right skips 15 seconds.
> Improve seeking controls with keyboard

- src/playbacks/html5_video/html5_video.js
Should fixes #1262 and maybe also deprecates #1254 .
> Fix url seek in HTML5 video playback.

- doc/BUILTIN_PLUGINS.md
- src/base/ui_object.js
- src/base/utils.js
- src/components/core/core.js
- src/playbacks/html5_video/html5_video.js
- test/base/utils_spec.js
See #1319 for example usage and technical explanations.
This change targets mobile devices and does not change current player behaviours.
Just set the `recycleVideo` playback option to `true` to enable this feature.
It should fixes a lot of issues on mobile and tablet devices (_single tap playback source load with autoplay, advert plugins, playlist plugins, ..._)
_EDIT: merged to single commit and updated explanations._
> Add HTML5 video element recycle feature.

- src/components/core/core.js
A bug happen when you load another source multiple times without destroying the player : it append another style element in DOM for each loaded source.
This fix prevents it by keeping a reference and properly remove existing element each render call.
> Fix core style element creation.

- src/base/playback.js
- src/components/player.js
- src/playbacks/html5_video/html5_video.js
__NOTE:__  this change is an addition to #1318 and therefore is only usefull if #1318 is merged.
This proposition targets mobile and tablet devices and does not change current player behaviours.
> On iOS and Android, playback of video must be initialized with a user action, meaning a tap or click. Once the <video> element has been activated within a user action, it will remain usable for programmatic control later.
These changes adds a `consent()` method to player which "capture" user action if called just after a tap or click event.
After method is called, you can perform any sync or async task before autoplay (even load another source and autoplay).
Initial goal of #1318 and this PR is to allow Clappr to behave like, for example, [Dailymotion](http://www.dailymotion.com/). (ie: load and …
> [PROPOSITION] user consent playback feature for mobile devices

- src/playbacks/hls/hls.js
While working on #1374 i thinked it could be convenient to be able to access to Hls.js library for constants.
Example usage :
```javascript
import Clappr from 'clappr'
const HLSJS = Clappr.HLS.HLSJS
let player = new Clappr.Player({
source: 'http://example.com/playlist.m3u8',
events: {
onError: e => {
if (e.error && e.error.evt === HLSJS.Events.ERROR) {
// Handle Hls.js error
}
}
}
});
```
> [PROPOSITION] Expose embedded hls.js library in hls playback.

- src/playbacks/html5_video/html5_video.js
In Google Chrome, `HTMLMediaElement.play()` returns a Promise which may trigger a DOMException when playback attempt has failed.
When it happen, it display the following error message in Google Chrome console :
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```
This fix simply catch the exception to avoid the error message to be displayed in console.
For more details, see [Google developers article](https://developers.google.com/web/updates/2016/03/play-returns-promise).
> Handle uncaught (in promise) DOMException with Chrome browser

- src/playbacks/hls/hls.js
- test/playbacks/hls_spec.js
Currently, if player try to load an HLS source playlist (_using hls.js playback_) which return a 40x or 50x error, then player is stalled.
The reason is that current code try to recover using `hls.startLoad()` on hls `NETWORK_ERROR`.
But according [documentation](https://github.com/video-dev/hls.js/blob/master/doc/design.md#error-detection-and-handling), the following network errors (_ErrorDetails_) cannot be recovered with `hls.startLoad()` : `MANIFEST_LOAD_ERROR`, `MANIFEST_LOAD_TIMEOUT` and `MANIFEST_PARSING_ERROR`.
This fix trigger a `PLAYBACK_ERROR` event to allow developer to decide how to handle the error. (_for example, using player `onError` configuration option_).
Usage example :
```javascript
var player = new Clappr.Player({
source: 'http://some.bad/path/playlist.m3u8',
events: …
```
> Enhance hls.js playback fatal network error handling.

- webpack-base-config.js
It fixes an issue introduced in new webpack dev server release.
Just be cautious about security warning described [here](https://github.com/webpack/webpack-dev-server/issues/882).
Also it seems that node `global` is required on dev player page, so i setted it to true.
> fix(webpack): fix webpack dev server configuration

- src/components/media_control/media_control.js
> fix(mediacontrol): fix getSettings method (fix iOS fullscreen button)

- package.json
- src/base/events.js
- test/base/events_spec.js
refs #1395 
the last bunch of package updates merged has increased our bundle size by 5kb
it went from 466kb ⇨ 471kb
this PR goes:
471kb ⇨ 470kb
I will try to add a task that checks the bundle size on each build so we can keep track of these increases
> remove lodash.once

- webpack.config.js
Fix an annoying issue where files in dist folder are deleted each time you run webpack dev server. (ie: `npm run start`).
> chore(webpack): avoid to load Clean plugin with npm run start

- doc/BUILTIN_PLUGINS.md
I updated the `recycleVideo` playback option documentation : some Firefox "desktop" browser version may sometime have an issue loading video. I recommend to use this option only with mobile devices.
> docs(playback): add isMobile workaround for recycleVideo playback option

- src/playbacks/base_flash_playback/public/flash.html
This fixe remove an unused legacy query parameter in base flash playback template (_movie param_).
It avoid IE11 to download twice the swf file. (_on player creation, the swf is downloaded once and second request is aborted. On player.load() the .swf file is downloaded only once_)
> Avoid IE11 to download .swf file twice

- src/components/loader/loader.js
- test/components/loader_spec.js
This fix plugin order when using external plugins.
EDIT:
Let's assume this code :
```javascript
class Toto extends FlasHLS {
// [...]
}
```
By adding `plugins: [Toto]` to player option, current loader removeDups() method will return :
```javascript
[ HLS(), HTML5Video(), HTML5Audio(), Flash(), Toto(), HTMLImg(), NoOp() ]
```
With fix :
```javascript
[ Toto(), HLS(), HTML5Video(), HTML5Audio(), Flash(), HTMLImg(), NoOp() ]
```
> fix(loader): update removeDups() to priorize external plugins

- src/base/utils.js
On iOS device (_playing HTML5 video_) if you call `Utils.Fullscreen.cancelFullscreen()` it will fail.
This fix allow you, to exit full screen programmatically. For example :
```javascript
const video = player.core.getCurrentPlayback().el // Assume <video> element
Utils.Fullscreen.cancelFullscreen(video)
```
It does **not** introduce any regression or breaking change.
_Tested on iPhone (Safari, Chrome), iPad (Safari, Chrome), MacOSX (Safari, Chrome, Firefox), Linux Debian (Chrome, Firefox); Window 7 (IE11, Chrome, Firefox), Windows 10 (Edge, Chrome, Firefox)._
> fix(utils): allow iOS device to exit fullscreen programmatically

- src/base/events.js
- src/components/browser.js
- src/components/core/core.js
This introduce a new core event (_only triggered on mobile devices_) when screen orientation has changed.
Motivations: It's a requirement for a feature i am working on : fullscreen on orientation change.
(_please note this PR only add screen orientation core event, not the fullscreen feature_)
Currently, fullscreen on orientation change work only on iOS devices because it is not a "true" fullscreen.
But hopefully it may be allowed in future browser versions. (_so it may be usefull for Clappr to be ready for this_).
> [PROPOSITION] Screen orientation detection for mobile device

- .babelrc
- package.json
refs #1395
470kb ⇨ 465kb
babel inlines the helper functions multiple times this plugin avoids that
> use babel transform runtime plugin to avoid duplicate babel helpers

- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
These changes allow autoplay on mobile devices when `mute` player option is set to true. (_and playback `playInline` is set to true on iOS_).
Thank you to @tomas2387 for original pull request #1260.
Example usage :
```javascript
var player = new Clappr.Player({
parentId: '#player-wrapper',
source: 'http://clappr.io/highline.mp4',
poster: 'http://clappr.io/poster.png',
mute: true,
autoPlay: true,
playback: { playInline: true }, // Required only by iOS
height: 360,
width: 640
});
```
Requirements :
* iOS version >= 10
* Android with Chrome version >= 53
supersede #1260, should fixes #1314
> mute or unmute video on volume change (muted autostart on mobile devices)

- src/components/media_control/media_control.js
Because of #1432 it is now possible to display at least the mute/unmute icon on media controls with Safari browser on mobile devices.
(_for example, it allow user to unmute video if autoplayed with mute option to true_).
> feat(media_control): allow mute/unmute video with Safari on mobile

- doc/PLAYER_ERRORS.md
A small update in player errors documentation to fix an issue with ErrorPlugin to avoid a possible jQuery conflict.
> docs(player_errors): use Clappr internal Zepto in second example

- src/playbacks/hls/hls.js
- src/playbacks/html5_video/html5_video.js
- src/plugins/closed_captions/closed_captions.js
Should fix #1471.
This is an experimental feature, as these kind of subtitles seems to be partially handled by hls.js library.
By partially, i mean it is properly displayed, but not all events are triggered and internal properties like `subtitleTracks` are not updated. (_always empty array returned_).
With hls live source, text track data may not immediatly available (_same for video element TextTrack objects_).
Another issue is that TextTrack cannot be removed from TextTrackList object. Since Clappr player destroy hls instance on player stop for live stream, then the next hls.js instance add more TextTrack objects to video element. (_obviously, cannot be currently fixed, maybe later with future specs_)
So i managed to find a workaround using …
> HLS live source closed caption support

- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
Without this change, every time the `HTML5Video` playback is initialized and the variable `_bufferingState` is `undefined` it will trigger (incorrectly) the `PLAYBACK_BUFFERFULL` event.
> Prevents wrong PLAYBACK_BUFFERFULL triggering

- src/base/events.js
- src/components/container/container.js
- src/playbacks/html5_video/html5_video.js
- test/components/container_spec.js
- test/playbacks/html5_video_spec.js
Today Clappr does not support 'seeked' event, sometime we need listen this event to realize one action when seek is finished.
I talked with @towerz and we discuss about the new architecture of Clappr, so we decided to implement this event only for playback.
> Add support to a seeked event

- src/playbacks/base_flash_playback/base_flash_playback.js
- test/playbacks/flash_spec.js
- test/playbacks/flashls_spec.js
- webpack-base-config.js
- webpack.config.js
Should fix #1480.
Previously it was working because the `url-loader` module internally use the `file-loader` module where public path default to webpack `__webpack_public_path__` global variable (_which is Webpack `output.publicPath` value_).
It seems that if you set the `publicPath` configuration parameter to `url-loader`, it is also passed to `file-loader`. So we can pass here the templated value and it is resolved at runtime instead of compilation time if set in `output.publicPath` (_i think it is because Clappr is writted in ES6_).
> fix(build): add templated public path to Webpack url-loader module config

- src/plugins/click_to_pause/click_to_pause.js
- test/plugins/click_to_pause_spec.js
Add missing tests and toggle css class only when necessary avoiding unnecessary DOM changes  on click to pause plugin
> Improve click to pause

- README.md
- doc/EXTERNAL_PLUGINS.md
Add image and link to [clappr-nerd-stats](https://github.com/lucasrodcosta/clappr-nerd-stats) plugin.
PS: Related to #711.
> Add clappr-nerd-stats plugin in README

- README.md
First, congrats - [clappr receives more than 400 M requests per month at jsDelivr](https://www.jsdelivr.com/package/npm/clappr), which makes it the 11th most popular package we host!
While our new back-end supports serving files from both npm and GitHub, we recommend always using only one of these methods for every package, with npm being the preferred one (using only npm means you can get detailed package usage statistics and npm packages are also searchable on our website).
I updated the links to use our npm endpoint.
> Update jsDelivr CDN links

- src/components/core/core.js
The core element needs to be immutable in DOM to avoid render problems and others unexpected behaviors (e.g. DFP freezed after a new load on Android)
> fix(core): Append core element to parent only once

- src/playbacks/hls/hls.js
- test/playbacks/hls_spec.js
Playback ready state treatment for not use html5 playback method.
Also, this pull request normalize the name of the setup methods between playbacks. The [dash playback](https://github.com/clappr/dash-shaka-playback) plugin already follows [this naming](https://github.com/clappr/dash-shaka-playback/blob/master/src/clappr-dash-shaka-playback.js#L257).
> Manage _ready() state on HLS playback

- package.json
- postcss.config.js
- src/components/core/public/style.scss
- src/components/media_control/public/media-control.scss
- src/playbacks/no_op/public/style.scss
- src/plugins/dvr_controls/public/dvr_controls.scss
- src/plugins/poster/public/poster.scss
- src/plugins/seek_time/public/seek_time.scss
- src/plugins/spinner_three_bounce/public/spinner.scss
- webpack-base-config.js
- yarn.lock
At the time of build for the project start or to run the test stack, warnings are appearing for me about mixins that Bourbon will deprecated in its new version `5.x.x`. 
In the repository of wrapper for Bourbon `node-bourbon` [has a issue about it](https://github.com/lacroixdesign/node-bourbon/issues/37) and it seems that the project is not using the most current version of Bourbon.
In the Bourbon repository there is an [issue talking about the project option](https://github.com/thoughtbot/bourbon/issues/702) and, according to them, `... we've decided to remove browser prefixing features from Bourbon.`
Alternatively, they suggest post-processors and the [Autoprefixer](https://github.com/postcss/autoprefixer) are best for this.
With this, I configured …
> Use Autoprefixer instead node-bourbon mixins

- src/base/ui_object.js
Small fix: `instanceof $` does not work with zepto as it does with jQuery, zepto has its own check `$.zepto.isZ(e)` -> https://github.com/madrobby/zepto/issues/349
> Fix is element instance of zepto

- src/playbacks/hls/hls.js
Whenever the player receives a playlist, the fillLevels method is executed, which causes the list of levels to be closed (if open) when using the default selection plugin. The user can't change level if stream server send playlists in low interval.
The playlist does not contain information about the video (bitrate), just the next chunks, because of that I removed the execution of the fillLevels method in _updatePlaybackType called by hls.js event LEVEL_LOADED.
> Do not call _fillLevels when receive a playlist (_updatePlaybackType)

- package.json
- webpack.config.js
Optionnaly builds with `devtool: 'inline-source-map'` webpack option.
Allows to debug with source-map even when bundle is embedded in consumer app and no Clappr sources are around. This is generally much more robust then plain source-maps when one wants to debug the package in the environment it gets shipped to as otherwise source paths of various dependencies may conflict or be collapsed over each others.
This adds a script `builld:debug` which will result in a *big* build that includes all the source-maps.
There is a log warning that this isn't suitable for prod. We probably don't need to commit this to the repo, it's only really necessary for debugging purpose in the specific situations described.
```
npm run build:debug
> clappr@0.2.80 build:debug clappr
> CLAPPR_INLINE_DEBUG=true …
```
> Optionnaly build with inline source maps (debug embedded bundle)

- src/components/core/core.js
- src/components/player.js
- test/player_spec.js
In the current implementation it's only possible to define events callbacks on player constructor.
This PR changes will:
- Allow set new events on configure method;
- Remove previous option event listeners when configure is called with a net set of events;
- Add tests for register option events listeners;
> Allow configure new events

- src/components/media_control/media_control.js
- test/components/media_control_spec.js
- **Issue 1:**
When reconfigure player, the mute option is ignored.
This change will allow reset the volume applying current mute option value.
- **Issue 2:**
Prevent the initial volume value from being persisted in the localStorage.
Possible issues: When a player instance is created with mute option enabled, the value 0 is persisted. When a new instance is created without this option (or mute=false), the 0 value will be restored as initial volume, causing an inconsistency.
> Fix - Reset volume/mute on configure

- src/components/core/core.js
- test/components/core_spec.js
TL/DR: The current implementation ignores the options object if it has a `source` or `sources` attribute.
This will cause an incorrect behavior: when user want to reconfigure some options and load a new source (at the same time), this will not happen, because the configure method will ignore the options in favor of loading the source.
This change will ensure that the two actions (load/configure) happen.
> Fix - Configure ignoring options when has source attribute

- src/base/utils.js
- src/playbacks/hls/hls.js
HLS.js rewrites passed config so after stopping and starting.
It fixes issue 1573
> Pass a copy of hlsjsConfig to HLS.js

- src/playbacks/hls/hls.js
Refactoring requested by issue #1183 
Changes
======
* Change `null` initial value of `_lastTimeUpdate` to `{ current: 0, total: 0 }`
* Move `_startTimeUpdateTimer()` from `constructor` to `play()`
> Trigger time update after play on HLS playback

- src/components/media_control/media_control.js
HD indicator disappears after calling render in case of settings update.
But it appears after stopping and starting playback.
> Fix disappearing hd indicator after render

- .yarnclean
_The `autoclean` command frees up space by removing unnecessary files and folders from dependencies. It reduces the number of files in your project’s `node_modules` folder ..._
**ref.:** https://yarnpkg.com/lang/en/docs/cli/autoclean/
------
> Remove unnecessary files from node_modules

- src/base/events.js
- src/components/core/core.js
- src/components/media_control/media_control.js
- test/components/media_control_spec.js
Summary of changes:
- add `MEDIACONTROL_OPTIONS_CHANGE` event for consistency with `Container`'s events
- add `configure` method to `MediaControl` and call it from `Core.configure` (TODO: check whether any `MediaControl`-specific options were actually changed before calling it, to prevent erroneous event triggering)
- add test
> enable MediaControl configuration after player creation

- doc/TROUBLESHOOTING.md
This corrects the link to the hls.js demo and adds links to the other tools mentioned in the TROUBLESHOOTING doc page.
> Improve links in troubleshooting docs

- doc/TROUBLESHOOTING.md
This renders as a broken, relative link otherwise, especially on GitHub's rendering of the .md doc.
> Update CDN link in troubleshooting docs

- src/playbacks/html5_video/html5_video.js
Delete src attribute on destroy instead set empty source.
This change will avoid the following HTML5 Video error:
```Code: 4, MEDIA_ELEMENT_ERROR: Empty src attribute```
> HTML5 Video: Avoid empty source error on destroy

- src/base/error_mixin.js
- src/components/container/container.js
- src/components/core/core.js
- src/components/error/error.js
- src/components/player.js
- test/base/playback_spec.js
- test/components/error_spec.js
The main change here is the addition of the method `createError`. The method was added to the `player`, `core` and `container` and now it's possible to create an error in these scopes.
> Error mixin expansion

- src/base/playback.js
- src/playbacks/html5_video/html5_video.js
- test/base/playback_spec.js
In addition to removing element this change removes listeners and undelegate events from playback.
This will stop triggering errors from destroyed video element that was still delegated.
> Use remove from ui object instead of zepto on playback

- src/components/player.js
- src/plugins/error_screen/error_screen.js
- src/plugins/poster/poster.js
Add an option to disable error screen plugin. This option also prevents the poster hides its play button when there is a fatal error.
> Add option to disable error screen plugin

- src/base/playback.js
- src/components/container/container.js
- test/components/container_spec.js
When player receive a new set of options, playback can use some of then.
With this PR, when `player.configure` was called the playback will update his internal copy of options, avoiding using old values when play.
> Add configure method on playback to allow update options

- src/playbacks/html5_video/html5_video.js
Following the same pattern applied on HLS and others playbacks, this PR will avoid triggering non-fatal errors on HTML5Video playback. The only action taken will be log this error as warn.
> refactor(html5_video): does not trigger warn errors

- doc/PLAYER_ERRORS.md
It fix player options scope issue in first example and use new `disableErrorScreen` player option introduced in #1642.
> docs(player_errors): update code of the examples

- src/playbacks/html5_video/html5_video.js
Setting volume property on tag video only if value !== 0
This can lock the mute/unmute action in some browsers/devices (e.g. Chrome + OnePlus)
> fix(html5_video):  Locked mute/unmute when setting any volume value

- doc/BUILTIN_PLUGINS.md
- src/components/media_control/media_control.js
It adds `hideMediaControlDelay` embed parameter in documentation.
It also fix and issue in the media control render method which does not take account of `hideMediaControlDelay` value. It currently have an hardcoded 1000 milliseconds default value.
__Note:__ i did not change the default value to 2000 (same value as [hide()](https://github.com/clappr/clappr/blob/master/src/components/media_control/media_control.js#L491) method) to avoid breaking change of the default behaviour. But i think it should be also changed to 2000 [instead of 1000](https://github.com/clappr/clappr/blob/master/src/components/media_control/media_control.js#L662).
So if Clappr core think it should be also changed to 2000, tell me and i modify the PR commit.
> fix: mediacontrol autohide timeout

- doc/BUILTIN_PLUGINS.md
- src/base/utils.js
- src/playbacks/html5_video/html5_video.js
- test/playbacks/html5_video_spec.js
It fixes an issue for mobile devices in the canAutoPlay method in html5 video playback : it does not rely anymore on the playback consented value because it may be reseted to false if source has changed (ie: playback re-created).
Fixes #1680.
> fix: mobile device autoplay

- src/plugins/seek_time/seek_time.js
When changes were introduced to work with extended attributes in m3u8 playlists, people that weren't using the attribute just saw ":/:" as a time
> Fix actualLiveServerTime when no offset supplied

- src/base/events.js
- src/components/core/core.js
- src/components/player.js
- test/components/core_spec.js
- test/player_spec.js
This PR creates a new event in core component and triggers that on resize, so we can effectively fire the event PLAYER_RESIZE.
> Fix player event onResize

- src/components/core/core.js
- test/components/core_spec.js
This PR brings back the computedSize property because there are third-party applications using it.
> fix(player): brings back computedSize property

- README.md
greenkeeper seems to be disabled and the 359 million hits/month is a nice stats from jsDelivr
> Add jsdelivr badge and remove greenkeeper

- src/base/utils.js
- src/playbacks/hls/hls.js
- test/base/utils_spec.js
- test/playbacks/hls_spec.js
> Add case insenstive check for HLS playback

- src/playbacks/html5_video/html5_video.js
It looks like it's been (broken) this way for a long time.
In addition, I observed that the `video.muted` property could be set to true while the `video.volume` > 0, and it still behaves muted.  We should check both of the properties.
> fix(playback) HTML5 playback isMuted function logic is inverted

- package.json
- yarn.lock
Hoping to get some of the new fixes (specifically the WebVTT enhancements) into Clappr ASAP
* https://github.com/video-dev/hls.js/releases/tag/v0.12.0
* https://github.com/video-dev/hls.js/releases/tag/v0.12.1
> chore(package): update hls.js to 0.12.1

- src/playbacks/html5_video/html5_video.js
When working with icecast audio and call `stop()` or `destroy()` methods, the source continues to load (forever).
Now it's fixed.
[Here you can see an example with icecast](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL3JldHJvNzAuaG9zdGluZ3JhZGlvLnJ1OjgwMjUvcmV0cm83MC0xMjgubXAzJywKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=)
Open dev tools -> Network and look: when the player is stopped the resource is still loading. When I have several icecast stations and switch between them, destroying the player each time, I end up with the situation when every resource is loading via several requests and new requests are …
> Fix: stop loading resource after stop() and destroy() methods are called

- src/components/player.js
Event `CORE_ACTIVE_CONTAINER_CHANGED` is triggered on the `Core` object. That's why it's needed to listen for this event of the `Core` object also :-)
> Listen for CORE_ACTIVE_CONTAINER_CHANGED on Core

- src/base/utils.js
- src/components/container/container.js
- test/base/utils_spec.js
Since the touch module [has been removed](https://github.com/clappr/clappr-zepto/commit/7dca838af14dab84ebbadef79a27abf45b70553d) from Clappr Zepto custom build, the container double tap/touch event is broken.
I googled about double tab and i make a quick fix based on this [jsFiddle](http://jsfiddle.net/brettwp/J4djY/).
I am not sure if this is the most elegant way to fix the issue, but it seems to work _(i tested on samsung galaxy, galaxy tab, iphone and ipad)_.
Should satisfy #1781.
> fix(container): handle double touch event

- src/playbacks/hls/hls.js
This PR fixes a leak of the timer from the HLS plugin. 
The problem happens when the method 'play` is called multiple times. This scenario can happen when the user pauses/play the video, for example.
For each time the `play` was being called, a new timer was being created and not being cleared when the playback was being destroyed.
This PR ensures that only one timer is running and, also, stop the timer when the playback is stopped.
> HLS - Fix interval timer leak

- src/components/container/container.js
- test/components/container_spec.js
This PR renames the handler of PLAYBACK_PROGRESS event on the container.
This is necessary because the method `progress` was being overwritten when the container is transformed into a promise. 
When this happens, some methods are included in its prototype: `[state, always, then, promise, done, fail, progress]`
The method `progress` is one of them, so if a new call to the `bindEvents` method happens when the method `progress` is overwritten, the reference is no longer the original `progress` method.
> Container - Avoid the override of the method progress

- doc/BUILTIN_PLUGINS.md
- src/playbacks/hls/hls.js
On iOS devices, HLS source triggers a fatal playback error if encryption key is denied.
This new `triggerFatalErrorOnResourceDenied` playback option, when set to true, will attempt to replicate this behaviour (ie: trigger playback fatal error).
It should satisfy #1809.
> feat: add triggerFatalErrorOnResourceDenied playback option

- src/base/events.js
- src/components/core/core.js
- src/plugins/media_control/media_control.js
This is a proposition to fix #1868 
It  adds the options object passed as argument to configure() method to the CORE_OPTIONS_CHANGE event.
This change allow media_control plugin to check if configure has been called with new source(s) and decide if it enable or not.
> fix(media_control): prevent mediacontrol to show calling configure with source

- src/components/container/public/style.scss
Because of the bootstrap container class the player doesn't go full screen, only half. After adding max-width, the bootstrap max-width is ignored and the player goes to proper full screen again.
> Fixed not fullscreen with Bootstrap

- src/base/svg_icons.js
- src/base/utils.js
- src/plugins/closed_captions/closed_captions.js
- src/plugins/error_screen/error_screen.js
- src/plugins/favicon/favicon.js
- src/plugins/media_control/media_control.js
- src/plugins/poster/poster.js
A simple proposition which should satisfy #1846.
It's a simple workaround to allow developper to override player SVG icons. _(in the meantime to implement a proper way)_.
Example usage :
```javascript
var customPlay = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 492.719 492.719" xml:space="preserve"><path d="M492.719,166.008c0-73.486-59.573-133.056-133.059-133.056c-47.985,0-89.891,25.484-113.302,63.569 c-23.408-38.085-65.332-63.569-113.316-63.569C59.556,32.952,0,92.522,0,166.008c0,40.009,17.729,75.803,45.671,100.178 l188.545,188.553c3.22,3.22,7.587,5.029,12.142,5.029c4.555,0,8.922-1.809,12.142-5.029l188.545-188.553 C474.988,241.811,492.719,206.017,492.719,166.008z"/></svg>';
// Override before create Clappr …
```
> feat(utils): add SVG icons module

- src/base/utils.js
- src/components/core/core.js
- test/components/core_spec.js
If fix fullscreen detection with Firefox browser. _(based on current fullscreen element)_
It also rename the Utils.Fullscreen `getFullscreenElement` method to `fullscreenElement` to be more consistent with [fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement).
> fix: repair fullscreen element detection with Firefox

- src/components/container/container.js
Current behavior:
```js
player.setVolume(0.9); // the volume will be set, you will hear the sound, but ...
player.getVolume(); // will return 0 
// and after:
player.mute();
player.unmute(); 
// you don't hear the sound anymore, since the stored value 0 is really set as the volume now
```
This PR fixes it and allows to use floats normally. To my mind, 1 is much louder than 0.5, so a float volume is a useful feature.
> Fix: sync stored volume value with the value passed to the playback and allow floats

- README.md
There is a small typo in README.md.
Should read `snippet` rather than `snipet`.
> docs: Fix simple typo, snipet -> snippet

- apps/clappr.io/docs/guides/plugins/metrics.md
- apps/clappr.io/docusaurus.config.js
- apps/clappr.io/i18n/pt-BR/code.json
- apps/clappr.io/i18n/pt-BR/docusaurus-plugin-content-blog/options.json
- apps/clappr.io/i18n/pt-BR/docusaurus-plugin-content-docs/current.json
- apps/clappr.io/i18n/pt-BR/docusaurus-plugin-content-docs/current/guides/plugins/metrics.md
- apps/clappr.io/i18n/pt-BR/docusaurus-theme-classic/footer.json
- apps/clappr.io/i18n/pt-BR/docusaurus-theme-classic/navbar.json
- apps/clappr.io/package.json
- apps/clappr.io/sidebars.js
- apps/clappr.io/src/components/GA4PluginSample/index.js
- apps/clappr.io/src/components/HomepageFeatures/index.js
- apps/clappr.io/src/pages/index.js
- yarn.lock
This PR configures the internationalization of Clappr's documentation into the pt-br language. The main features are:
- i18n setup for pt-br language
- Translation of the main doc components
- Addition of a tutorial on building metrics plugins and their translation (example, can be modified)
To run the documentation in the pt-br version use: `yarn start --locale=pt-BR `
> Setup i18n for documentation

- packages/hlsjs-playback/src/hls.js
- packages/hlsjs-playback/src/hls.test.js
When the `play` method was called more than once while loading the manifest, the playback called `loadSource` again, restarting the loading process.
This happened because the flag `_manifestParsed` was set on `Events.MANIFEST_PARSED` which is async.
By waiting for `MANIFEST_LOADING`, the flag is set on the `loadSource` call, preventing the `loadSource` from being called again on a `play` method call.
> Fix (hlsjs-playback) - Prevent calling loadSource multiple times while loadind manifest

- packages/clappr-core/src/base/events/events.js
- packages/clappr-core/src/base/events/events.test.js
- packages/clappr-core/src/components/container/container.js
- packages/clappr-core/src/components/core/core.js
- packages/clappr-core/src/playbacks/html5_video/html5_video.js
When the player is destroyed, the references and timers should be removed to prevent memory leaks.
Besides that, a fix to `stopListening` was made to allow stopping a `listenToOnce` event handler sending the callback as argument to `stopListening`.
> Fix - Avoid memory leaks

- .eslintrc.js
- packages/clappr-core/src/components/log/log.js
- packages/clappr-core/src/playbacks/html5_video/html5_video.js
- packages/clappr-core/src/playbacks/html5_video/html5_video.test.js
- packages/dash-shaka-playback/src/clappr-dash-shaka-playback.js
- packages/hlsjs-playback/package.json
- packages/hlsjs-playback/src/hls.js
- packages/player/rollup.config.js
- packages/player/src/base_bundle.js
- yarn.lock
This MR brings several improvements and fixes listed below:
- `hlsjs-playback`
- Upgrade hls.js to the latest version (1.5.14) #2146
- Prevent playback from staying paused when recovering from hlsjs media error
- `dash-shaka-playback`
- Add more error-related info from the shaka player to the `playback_error` event payload
- Prevent accumulation of `setIntervals`
- `hlsjs-playback`, `dash-shaka-playback`
- Reduce the number of calls of `timeupdate` events
- `hlsjs-playback`, `dash-shaka-playback` and `html5_video`
- Fix the DVR state when pausing/seeking externally from the player and remove duplicated code
- `Log`
- Add `core:mousemove` to exclude list
- Check by level before looking into `exclude_list` array
> Playback fixes/updates and performance improvements

- packages/hlsjs-playback/src/hls.js
This MR changes the LEVEL_SWITCHING event to LEVEL_SWITCHED in order to capture the bitrate change correctly at the beginning of the video.
> Change LEVEL_SWITCHING event to LEVEL_SWITCHED

- packages/clappr-core/src/components/container/container.js
This PR removes `animate()` method from `container.js`.
The method is an old implementation from Zepto that was replaced by clappr-zepto. In clappr-zepto, the animate() method does not exist, so it appears that it is no longer used.
> Remove unused animate method from container

- .commitlintrc.js
- lerna.json
- package.json
- yarn.lock
This pull request includes changes to simplify the commit linting configuration and update the release message format. The most important changes include removing the `@commitlint/config-lerna-scopes` configuration and updating the release message format in `lerna.json`.
Commit linting configuration updates:
* [`.commitlintrc.js`](diffhunk://#diff-faef10fb1c732cbc23a0af952f176125d404c6b6bff0c13e88cb14c95674b462L3-R3): Removed the `@commitlint/config-lerna-scopes` configuration.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22): Removed the `@commitlint/config-lerna-scopes` dependency.
Release message format update:
* [`lerna.json`](diffhunk://#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821L9-R9): Updated the …
> Remove lerna scopes

- packages/clappr-core/package.json
This pull request includes a small change to the `packages/clappr-core/package.json` file. The change modifies the `bundle-check` script to include a TypeScript compilation step.
* [`packages/clappr-core/package.json`](diffhunk://#diff-7ed5fc5d22083b11fa490f432292bd05f88d9ca962c19a877f82538635b916faL9-R9): Updated the `bundle-check` script to run `tsc` after the rollup command.
> Fix: Add types to release

- packages/clappr-core/package.json
This pull request includes a small change to the `packages/clappr-core/package.json` file. The change adds the `/types` directory to the list of files that are included when the package is published.
> chore: include types dir to npm files

- apps/clappr.io/src/components/HomepageFeatures/index.js
I added the following resources: 
1) If "Feature" components don't change frequently, I put "React.memo" to avoid unnecessary rendering and improve performance.
2) To simplify the code, I destructured the props directly in the map, which makes reading a little easier.
3) I added the "aria-label" attribute to read the SVG and become it acessible to screen readers.
> Fix - add React memo, aria-label in SVG and desestruturing properites

- packages/clappr-plugins/src/vendor/kibo.js
This MR check if `beforeunload` event is available and remove `unload` deprecated event from Kibo lib.
> Remove deprecated unload event from Kibo

- packages/hlsjs-playback/src/hls.js
Add liveSyncPosition getter into Hlsjs to get the position of live sync point in low latency streams
> feat(hlsjs): add liveSyncPosition getter

- packages/clappr-core/.eslintrc.json
- packages/clappr-core/package.json
- packages/clappr-core/src/components/core/core.js
- yarn.lock
Enhanced the core resize event to fall back on `options.width` when `el.clientWidth` is unavailable.
In Node.js environments, the Clappr's Core `resize` event was emitting events with an `undefined` size. This happened because two methods depended on `el.clientWidth`, but in these environments, `el` is often an empty object. This refactor ensures that when `el.clientWidth` is not present, the resize event will use `options.width` as a fallback.
This adjustment improves consistency, as `options.width` was already part of the event logic, and it does not affect behavior on web browsers or HTML-based TV platforms.
> Refactor – Adjust Core Resize Event

- packages/hlsjs-playback/package.json
- yarn.lock
This pull request updates the `hls.js` dependency in the `packages/hlsjs-playback` package to a newer version. Both the `peerDependencies` and `devDependencies` sections of the `package.json` file have been updated to use version `1.6.2`
> Update hls.js to v1.6.2
